<?php
/**
 * CertificateErrorErrorTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  EcuaapiSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ECUAPI - Electronic Invoicing API
 *
 * API for electronic invoicing in Ecuador. Generate, sign, and send invoices to SRI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ecuabyte.lat
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace EcuaapiSdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CertificateErrorErrorTest Class Doc Comment
 *
 * @category    Class
 * @description CertificateErrorError
 * @package     EcuaapiSdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CertificateErrorErrorTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CertificateErrorError"
     */
    public function testCertificateErrorError()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "code"
     */
    public function testPropertyCode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "message"
     */
    public function testPropertyMessage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
