<?php
/**
 * HealthApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  EcuaapiSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ECUAPI - Electronic Invoicing API
 *
 * API for electronic invoicing in Ecuador. Generate, sign, and send invoices to SRI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ecuabyte.lat
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace EcuaapiSdk\Test\Api;

use \EcuaapiSdk\Configuration;
use \EcuaapiSdk\ApiException;
use \EcuaapiSdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * HealthApiTest Class Doc Comment
 *
 * @category Class
 * @package  EcuaapiSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class HealthApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for healthGet
     *
     * Basic health check.
     *
     */
    public function testHealthGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for healthHealthGet
     *
     * Detailed health check.
     *
     */
    public function testHealthHealthGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1HealthGet
     *
     * Basic health check.
     *
     */
    public function testV1HealthGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1HealthHealthGet
     *
     * Detailed health check.
     *
     */
    public function testV1HealthHealthGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
