<?php
/**
 * InvoicesApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  EcuaapiSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ECUAPI - Electronic Invoicing API
 *
 * API for electronic invoicing in Ecuador. Generate, sign, and send invoices to SRI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ecuabyte.lat
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace EcuaapiSdk\Test\Api;

use \EcuaapiSdk\Configuration;
use \EcuaapiSdk\ApiException;
use \EcuaapiSdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * InvoicesApiTest Class Doc Comment
 *
 * @category Class
 * @package  EcuaapiSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class InvoicesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for v1InvoicesGet
     *
     * List invoices.
     *
     */
    public function testV1InvoicesGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1InvoicesIdAuthorizePost
     *
     * Authorize invoice.
     *
     */
    public function testV1InvoicesIdAuthorizePost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1InvoicesIdDelete
     *
     * Void invoice.
     *
     */
    public function testV1InvoicesIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1InvoicesIdGet
     *
     * Get invoice by ID.
     *
     */
    public function testV1InvoicesIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1InvoicesIdPdfGet
     *
     * Download RIDE PDF.
     *
     */
    public function testV1InvoicesIdPdfGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1InvoicesIdSendPost
     *
     * Send invoice to SRI.
     *
     */
    public function testV1InvoicesIdSendPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1InvoicesIdXmlGet
     *
     * Download signed XML.
     *
     */
    public function testV1InvoicesIdXmlGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1InvoicesPost
     *
     * Create invoice.
     *
     */
    public function testV1InvoicesPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
